presubmits:
  - name: presubmit-api-go-test
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - make
        args:
        - unit
  - name: presubmit-api-gosec
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - make
        args:
        - gosec
  - name: presubmit-api-golangci-lint
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - make
        args:
        - lint
  - name: presubmit-api-license-header-check
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - "/bin/sh"
        - "-c"
        - |
          /usr/local/bin/checklicense.sh > ${ARTIFACTS}/license_headers_results.txt
  - name: presubmit-api-scancode-toolkit
    decorate: true
    always_run: true
    spec:
      containers:
      - image: nephio/scancode-toolkit:v31.2.5
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          /scancode-toolkit/scancode --ignore "whitelist.json" -clpeui -n 2 --html ${ARTIFACTS}/scancode_report.html . --tallies-with-details
        resources:
          requests:
            cpu: 2
            memory: 1Gi
  - name: presubmit-api-fossology
    decorate: true
    always_run: true
    spec:
      containers:
      - image: fossology/fossology:scanner
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |
          /bin/fossologyscanner repo nomos ojo copyright keyword
          cp -R results ${ARTIFACTS}/
  - name: presubmit-api-lichen
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - "/usr/local/bin/lichen.sh"
