//go:build !ignore_autogenerated

/*
Copyright 2023 Nephio.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nssai) DeepCopyInto(out *Nssai) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nssai.
func (in *Nssai) DeepCopy() *Nssai {
	if in == nil {
		return nil
	}
	out := new(Nssai)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlmnInfo) DeepCopyInto(out *PlmnInfo) {
	*out = *in
	if in.NssaiList != nil {
		in, out := &in.NssaiList, &out.NssaiList
		*out = make([]Nssai, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlmnInfo.
func (in *PlmnInfo) DeepCopy() *PlmnInfo {
	if in == nil {
		return nil
	}
	out := new(PlmnInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RanConfig) DeepCopyInto(out *RanConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RanConfig.
func (in *RanConfig) DeepCopy() *RanConfig {
	if in == nil {
		return nil
	}
	out := new(RanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RanConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RanConfigList) DeepCopyInto(out *RanConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RanConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RanConfigList.
func (in *RanConfigList) DeepCopy() *RanConfigList {
	if in == nil {
		return nil
	}
	out := new(RanConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RanConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RanConfigSpec) DeepCopyInto(out *RanConfigSpec) {
	*out = *in
	in.PlmnInfo.DeepCopyInto(&out.PlmnInfo)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RanConfigSpec.
func (in *RanConfigSpec) DeepCopy() *RanConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RanConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RanConfigStatus) DeepCopyInto(out *RanConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RanConfigStatus.
func (in *RanConfigStatus) DeepCopy() *RanConfigStatus {
	if in == nil {
		return nil
	}
	out := new(RanConfigStatus)
	in.DeepCopyInto(out)
	return out
}
