//go:build !ignore_autogenerated

/*
Copyright 2023 Nephio.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmfConfig) DeepCopyInto(out *AmfConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmfConfig.
func (in *AmfConfig) DeepCopy() *AmfConfig {
	if in == nil {
		return nil
	}
	out := new(AmfConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AmfConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmfConfigList) DeepCopyInto(out *AmfConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AmfConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmfConfigList.
func (in *AmfConfigList) DeepCopy() *AmfConfigList {
	if in == nil {
		return nil
	}
	out := new(AmfConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AmfConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmfConfigSpec) DeepCopyInto(out *AmfConfigSpec) {
	*out = *in
	if in.ServedGuami != nil {
		in, out := &in.ServedGuami, &out.ServedGuami
		*out = make([]ServedGuamiConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmfConfigSpec.
func (in *AmfConfigSpec) DeepCopy() *AmfConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AmfConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmfConfigStatus) DeepCopyInto(out *AmfConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmfConfigStatus.
func (in *AmfConfigStatus) DeepCopy() *AmfConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AmfConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmfId) DeepCopyInto(out *AmfId) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmfId.
func (in *AmfId) DeepCopy() *AmfId {
	if in == nil {
		return nil
	}
	out := new(AmfId)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonCoreRANConfig) DeepCopyInto(out *CommonCoreRANConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonCoreRANConfig.
func (in *CommonCoreRANConfig) DeepCopy() *CommonCoreRANConfig {
	if in == nil {
		return nil
	}
	out := new(CommonCoreRANConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CommonCoreRANConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonCoreRANConfigList) DeepCopyInto(out *CommonCoreRANConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CommonCoreRANConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonCoreRANConfigList.
func (in *CommonCoreRANConfigList) DeepCopy() *CommonCoreRANConfigList {
	if in == nil {
		return nil
	}
	out := new(CommonCoreRANConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CommonCoreRANConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonCoreRANConfigSpec) DeepCopyInto(out *CommonCoreRANConfigSpec) {
	*out = *in
	if in.PlmnInfo != nil {
		in, out := &in.PlmnInfo, &out.PlmnInfo
		*out = make([]PlmnInfoConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CommunicationModel != nil {
		in, out := &in.CommunicationModel, &out.CommunicationModel
		*out = make([]CommunicationModelConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonCoreRANConfigSpec.
func (in *CommonCoreRANConfigSpec) DeepCopy() *CommonCoreRANConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CommonCoreRANConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonCoreRANConfigStatus) DeepCopyInto(out *CommonCoreRANConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonCoreRANConfigStatus.
func (in *CommonCoreRANConfigStatus) DeepCopy() *CommonCoreRANConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CommonCoreRANConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunicationModelConfig) DeepCopyInto(out *CommunicationModelConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunicationModelConfig.
func (in *CommunicationModelConfig) DeepCopy() *CommunicationModelConfig {
	if in == nil {
		return nil
	}
	out := new(CommunicationModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnnInfo) DeepCopyInto(out *DnnInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnnInfo.
func (in *DnnInfo) DeepCopy() *DnnInfo {
	if in == nil {
		return nil
	}
	out := new(DnnInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nssai) DeepCopyInto(out *Nssai) {
	*out = *in
	if in.DnnInfo != nil {
		in, out := &in.DnnInfo, &out.DnnInfo
		*out = make([]DnnInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nssai.
func (in *Nssai) DeepCopy() *Nssai {
	if in == nil {
		return nil
	}
	out := new(Nssai)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlmnId) DeepCopyInto(out *PlmnId) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlmnId.
func (in *PlmnId) DeepCopy() *PlmnId {
	if in == nil {
		return nil
	}
	out := new(PlmnId)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlmnInfoConfig) DeepCopyInto(out *PlmnInfoConfig) {
	*out = *in
	if in.Nssai != nil {
		in, out := &in.Nssai, &out.Nssai
		*out = make([]Nssai, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlmnInfoConfig.
func (in *PlmnInfoConfig) DeepCopy() *PlmnInfoConfig {
	if in == nil {
		return nil
	}
	out := new(PlmnInfoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServedGuamiConfig) DeepCopyInto(out *ServedGuamiConfig) {
	*out = *in
	out.PlmnId = in.PlmnId
	out.AmfId = in.AmfId
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServedGuamiConfig.
func (in *ServedGuamiConfig) DeepCopy() *ServedGuamiConfig {
	if in == nil {
		return nil
	}
	out := new(ServedGuamiConfig)
	in.DeepCopyInto(out)
	return out
}
